apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public-envoy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-north-1:092620891680:certificate/23dedb1b-67b7-414e-8d2d-a521d4ed1dee"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/ready"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "19003"
          service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=production,ManagedBy=EnvoyGateway"