aws_region                   = "eu-north-1"
environment                  = "production"
cluster_name                 = "eks"
kubernetes_version           = "1.35"
vpc_cidr                     = "10.0.0.0/16"
azs                          = ["eu-north-1a", "eu-north-1b", "eu-north-1c"]
domain_name                  = "dglobaleng.com.ng"
acm_certificate_arn          = "arn:aws:acm:eu-north-1:092620891680:certificate/23dedb1b-67b7-414e-8d2d-a521d4ed1dee"
github_repository            = "https://github.com/amadidominic15/cloudkitchen-gitops.git"
node_instance_types          = ["c7i-flex.large"]
endpoint_public_access_cidrs = ["YOUR_PUBLIC_IP/32"]
admin_principal_arn          = "arn:aws:iam::092620891680:user/admin"
loki_chunks_bucket           = "cloudkitchen-gitops-chunks"
loki_ruler_bucket            = "cloudkitchen-gitops-ruler"
private_subnets              = ["10.0.0.0/24"]
public_subnets               = ["10.0.32.0/24"]
ecr_repositories             = ["frontend", "users", "products", "orders", "payments", "notifications"]
server_replicas              = 2
controller_replicas          = 2
repo_server_replicas         = 2
application_set_replicas     = 2
replica_count                = 2
deployment_replicas          = 2
